global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "obelix_metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["obelix-webshop:8080", "obelix-quarry:8081"]
